name: 哔咔漫画自动打哔咔

on:
  workflow_dispatch:
  schedule:
    - cron: "00 20 * * *"
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # 顺便升级一下 checkout 到 v3 或 v4

      - name: "Set up Python"
        # 关键修改：从 @v1 升级到 @v5
        # v5 版本非常强大，如果环境里没有 Python，它会自动去下载安装
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'   # 建议改为 3.10，既稳定又支持新环境

      - name: "安装依赖包"
        run: pip install -r ./requirements.txt

      - name: "运行 哔咔漫画自动打哔咔"
        run: python3 function/bika/bika.py
        env:
          BIKA_USER: ${{ secrets.BIKA_USER }}
          BIKA_PASS: ${{ secrets.BIKA_PASS }}
          SEND_KEY: ${{ secrets.SEND_KEY }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN}}
          PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER}}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          QYWX_AM: ${{ secrets.QYWX_AM}}
